from app.services.veiculo_service import (cadastrar_veiculo)

veiculos = []

resultado1 = cadastrar_veiculo(veiculos, "abc-1234", "Fiat", "palio", 130000)
resultado2 = cadastrar_veiculo(veiculos, "efg-5678", "Fiat", "mobi", 190000)
resultado3 = cadastrar_veiculo(veiculos, "efg-5678", "Fiat", "uno", 190000)
print(resultado1)
print(resultado2)
print(resultado3)
print("Quantidade de veiculos cadastrados: ", len(veiculos))
print(veiculos[0].numero_frota)
print(veiculos[0].placa)
print(veiculos[0].marca)
print(veiculos[0].modelo)
print(veiculos[0].km)
print(veiculos[0].ativo)
print(veiculos[1].numero_frota)
print(veiculos[1].placa)
print(veiculos[1].marca)
print(veiculos[1].modelo)
print(veiculos[1].km)
print(veiculos[1].ativo)
print(veiculos[2].numero_frota)
print(veiculos[2].placa)
print(veiculos[2].marca)
print(veiculos[2].modelo)
print(veiculos[2].km)
print(veiculos[2].ativo)